            "static SageValue sage_exec(SageValue cmd) {\n"
            "    if (cmd.type != SAGE_TAG_STRING) return sage_number(-1);\n"
            "    int res = system(cmd.as.string);\n"
            "    return sage_number((double)res);\n"
            "}\n"
            "static SageValue sage_readfile(SageValue path) {\n"
            "    if (path.type != SAGE_TAG_STRING) return sage_nil();\n"
            "    FILE* f = fopen(path.as.string, \"rb\");\n"
            "    if (!f) return sage_nil();\n"
            "    size_t capacity = 4096;\n"
            "    size_t size = 0;\n"
            "    char* buf = malloc(capacity);\n"
            "    size_t n;\n"
            "    while ((n = fread(buf + size, 1, capacity - size - 1, f)) > 0) {\n"
            "        size += n;\n"
            "        if (size >= capacity - 1) {\n"
            "            capacity *= 2;\n"
            "            buf = realloc(buf, capacity);\n"
            "        }\n"
            "    }\n"
            "    buf[size] = '\\0';\n"
            "    fclose(f);\n"
            "    SageValue res = sage_string(buf);\n"
            "    free(buf);\n"
            "    return res;\n"
            "}\n"
            "static SageValue sage_writefile(SageValue path, SageValue content) {\n"
            "    if (path.type != SAGE_TAG_STRING || content.type != SAGE_TAG_STRING) return sage_nil();\n"
            "    FILE* f = fopen(path.as.string, \"wb\");\n"
            "    if (!f) return sage_nil();\n"
            "    fputs(content.as.string, f);\n"
            "    fclose(f);\n"
            "    return sage_nil();\n"
            "}\n"
            "static SageValue sage_getenv(SageValue name) {\n"
            "    if (name.type != SAGE_TAG_STRING) return sage_nil();\n"
            "    char* val = getenv(name.as.string);\n"
            "    if (!val) return sage_nil();\n"
            "    return sage_string(val);\n"
            "}\n"
            "static SageValue sage_substr(SageValue s, SageValue start, SageValue len) {\n"
            "    if (s.type != SAGE_TAG_STRING || start.type != SAGE_TAG_NUMBER || len.type != SAGE_TAG_NUMBER) return sage_string(\"\");\n"
            "    int st = (int)start.as.number;\n"
            "    int l = (int)len.as.number;\n"
            "    int slen = strlen(s.as.string);\n"
            "    if (st < 0) st = 0;\n"
            "    if (st > slen) st = slen;\n"
            "    if (st + l > slen) l = slen - st;\n"
            "    if (l < 0) l = 0;\n"
            "    char* res = malloc(l + 1);\n"
            "    strncpy(res, s.as.string + st, l);\n"
            "    res[l] = '\\0';\n"
            "    SageValue val = sage_string(res);\n"
            "    free(res);\n"
            "    return val;\n"
            "}\n"
            "static SageValue sage_platform_fn(void) {\n"
            "    return sage_string(\"linux\");\n"
            "}\n"
